baseURL: https://www.buschlab.org/
languageCode: en-gb
title: Busch Lab
disableKinds: [taxonomy, taxonomyTerm, RSS, sitemap, robotsTXT]
disableHugoGeneratorInject: true
metaDataFormat: yaml
theme: buschlab
sectionPagesMenu: main
menu:
  main:
  - identifier: zmp
    name: ZMP
    url: https://zmp.buschlab.org/
