name = "buschlab"
license = "AGPL-3.0"
licenselink = "https://www.gnu.org/licenses/agpl-3.0.txt"
description = "Busch Lab theme"
homepage = "https://www.buschlab.org/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Ian Sealy"
  homepage = "https://www.iansealy.com/"
